parameters:
  - name: modulesToCache
    displayName: Module Target Directories to Cache
    type: object
    default:
      modules:
        - org.hl7.fhir.utilities
        - org.hl7.fhir.dstu2
        - org.hl7.fhir.dstu2016may
        - org.hl7.fhir.dstu3
        - org.hl7.fhir.r4
        - org.hl7.fhir.r4b
        - org.hl7.fhir.r5
        - org.hl7.fhir.convertors
        - org.hl7.fhir.validation
        - org.hl7.fhir.validation.cli
        - org.hl7.fhir.report
  - name: modulesToTest
    displayName: Modules to Test
    type: object
    default:
      modules:
        - org.hl7.fhir.utilities
        - org.hl7.fhir.dstu2
        - org.hl7.fhir.dstu2016may
        - org.hl7.fhir.dstu3
        - org.hl7.fhir.r4
        - org.hl7.fhir.r4b
        - org.hl7.fhir.r5
        - org.hl7.fhir.convertors
        - org.hl7.fhir.validation
      multiplatformModules:
        - org.hl7.fhir.utilities
  - name: testConfigurations
    displayName: VM Images and JDKs to Test Against
    type: object
    default:
      configurations:
        - name: ubuntu-java-11
          image: ubuntu-latest
          jdk: 1.11
          javaToolOptions:
        - name: ubuntu-java-17
          image: ubuntu-latest
          jdk: 1.17
          javaToolOptions:
        - name: ubuntu-java-11-cp1252
          image: ubuntu-latest
          jdk: 1.11
          javaToolOptions: -Dfile.encoding=Cp1252
        - name: windows-java-11
          image: windows-latest
          jdk: 1.11
          javaToolOptions:
        - name: windows-java-17
          image: windows-latest
          jdk: 1.17
          javaToolOptions:
        - name: macos-java-11
          image: macos-latest
          jdk: 1.11
          javaToolOptions:
        - name: macos-java-17
          image: macos-latest
          jdk: 1.17
          javaToolOptions:
  - name: jdksToTest
    displayName: JDKs to Test Against
    type: object
    default:
      jdks:
        - 1.11
        - 1.17

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: setup
    displayName: Cache Maven Artifacts and Build Targets
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 1
      - task: Cache@2
        displayName: Cache maven artifacts
        inputs:
          key: maven | $(Build.BuildId) | artifacts
          path: $(MAVEN_CACHE_FOLDER)
      - template: cache-target-tasks-template.yml
        parameters:
          modules:
            ${{ parameters.modulesToCache.modules }}
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: mkdir -p $(MAVEN_CACHE_FOLDER); pwd; ls -al $(MAVEN_CACHE_FOLDER)
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -DskipTests'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'install'
  - template: test-unit-jobs-template.yml
    parameters:
      testUnits:
        - ${{ each configuration in parameters.testConfigurations.configurations }}:
          - name: ${{ configuration.name }}
            vmImage: ${{ configuration.image }}
            javaToolOptions:  ${{ configuration.javaToolOptions }}
            jdkVersion: ${{ configuration.jdk }}
            ${{ if eq(configuration.name, 'ubuntu-java-11') }}:
              skipJaCoCo: false
              modules:
                  ${{ parameters.modulesToTest.modules }}
            ${{ else }}:
              skipJaCoCo: true
              modules:
                ${{ parameters.modulesToTest.multiplatformModules }}
  - template: test-cli-exec-job-template.yml
    parameters:
      testUnits:
        - ${{ each configuration in parameters.testConfigurations.configuration }}:
          - vmImage: ${{ configuration.image }}
            jdkVersion: ${{ configuration.jdk }}

