trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: setup
    displayName: cache-maven-dependencies
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 1
      - task: Cache@2
        displayName: Cache maven artifacts
        inputs:
          key: maven | $(Build.BuildId) | artifacts
          path: $(MAVEN_CACHE_FOLDER)
      - template: cache-target-directory-tasks.yml
        parameters:
          modules:
            - org.hl7.fhir.utilities
            - org.hl7.fhir.dstu2
            - org.hl7.fhir.dstu2016may
            - org.hl7.fhir.dstu3
            - org.hl7.fhir.r4
            - org.hl7.fhir.r4b
            - org.hl7.fhir.r5
            - org.hl7.fhir.convertors
            - org.hl7.fhir.validation
            - org.hl7.fhir.validation.cli
            - org.hl7.fhir.report
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: mkdir -p $(MAVEN_CACHE_FOLDER); pwd; ls -al $(MAVEN_CACHE_FOLDER)
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -DskipTests'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'install'
  - template: test-module-jobs.yml
    parameters:
      vmImage: ubuntu-latest
      modules:
        - org.hl7.fhir.utilities
        - org.hl7.fhir.dstu2
        - org.hl7.fhir.dstu2016may