parameters:
  - name: modulesToCache
    displayName: Module Target Directories to Cache
    type: object
    default:
      modules:
        - org.hl7.fhir.utilities
        - org.hl7.fhir.dstu2
        - org.hl7.fhir.dstu2016may
        - org.hl7.fhir.dstu3
        - org.hl7.fhir.r4
        - org.hl7.fhir.r4b
        - org.hl7.fhir.r5
        - org.hl7.fhir.convertors
        - org.hl7.fhir.validation
        - org.hl7.fhir.validation.cli
        - org.hl7.fhir.report
  - name: modulesToTest
    displayName: Modules to Test
    type: object
    default:
      modules:
        - org.hl7.fhir.utilities
        - org.hl7.fhir.dstu2
        - org.hl7.fhir.dstu2016may
        - org.hl7.fhir.dstu3
        - org.hl7.fhir.r4
        - org.hl7.fhir.r4b
        - org.hl7.fhir.r5
        - org.hl7.fhir.convertors
        - org.hl7.fhir.validation
  - name: vmImagesToTest
    displayName: VM Images to Test Against
    type: object
    default:
      images:
        - ubuntu-latest
        - windows-latest
        - mac-latest
  - name: jdksToTest
    displayName: JDKs to Test Against
    type: object
    default:
      jdks:
        - 1.11
        - 1.17

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: setup
    displayName: cache-maven-dependencies
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 1
      - task: Cache@2
        displayName: Cache maven artifacts
        inputs:
          key: maven | $(Build.BuildId) | artifacts
          path: $(MAVEN_CACHE_FOLDER)
      - template: cache-target-tasks-template.yml
        parameters:
          modules:
            ${{ parameters.modulesToCache.modules }}
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: mkdir -p $(MAVEN_CACHE_FOLDER); pwd; ls -al $(MAVEN_CACHE_FOLDER)
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -DskipTests'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'install'
  - template: test-unit-jobs-template.yml
    parameters:
      testUnits:
        - vmImage: windows-latest
          javaToolOptions: -Dfile.encoding=Cp1252
          jdkVersion: 1.11
          skipJaCoCo: true
          modules:
            ${{ parameters.modulesToTest.modules }}
        - vmImage: ubuntu-latest
          javaToolOptions:
          jdkVersion: 1.11
          skipJaCoCo: false
          modules:
            ${{ parameters.modulesToTest.modules }}
  - template: test-cli-exec-job-template.yml
    parameters:
      testUnits:
        ${{ each image in parameters.vmImagesToTest.images }}:
          - vmImage: ${{ image }}
            jdkVersion: 1.11

