jobs:
  - ${{ each unit in parameters.testUnits }}:
    - ${{ each value in unit.modules }}:
      - job: ${{unit.name}}-${{value}}
        dependsOn: [ 'setup' ]

        displayName: ${{unit.name}}-${{value}}

        pool:
          vmImage: ${{unit.vmImage}}

        variables:
          JAVA_TOOL_OPTIONS: ${{unit.javaToolOptions}}

        steps:
        - task: Cache@2
          displayName: Cache maven artifacts
          inputs:
            key: maven | $(Build.BuildId) | artifacts
            path: $(MAVEN_CACHE_FOLDER)
        - template: cache-target-tasks-template.yml
          parameters:
            modules:
              - ${{ value }}
          # Runs 'mvn install'
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -pl ${{value}} -Djacoco.skip=${{unit.skipJaCoCo}}'
            mavenOptions: '-Xmx768m -Dmaven.resolver.transport=wagon'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '${{unit.jdkVersion}}'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'test'
  - job: publish_codecov
    dependsOn:
      - ${{ each module in parameters.modulesToTest.modules }}:
          - ubuntu-java-11-${{ module }}
      - ubuntu-java-11-org.hl7.fhir.utilities
    displayName: Publish Codecov Results

    pool:
      vmImage: ubuntu-latest

    steps:
      - script: bash echo "Placeholder for codecov"
        displayName: 'codecov Bash Uploader'