jobs:
  - ${{ each value in parameters.modules }}:
      - job:
        dependsOn: [ 'setup' ]

        displayName: ${{parameters.vmImage}} ${{value}}

        pool:
          vmImage: ${{parameters.vmImage}}

        steps:
        - task: Cache@2
          displayName: Cache maven artifacts
          inputs:
            key: maven | $(Build.BuildId) | artifacts
            path: $(MAVEN_CACHE_FOLDER)
        - template: cache-target-directory-tasks.yml
          parameters:
            modules:
              - ${{ value }}
          # Runs 'mvn install'
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -pl $(value)'
            mavenOptions: '-Xmx768m -Dmaven.resolver.transport=wagon'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '${{parameters.jdkVersion}}'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'test'