jobs:
  - ${{ each unit in parameters.testUnits }}:
    - ${{ each value in unit.modules }}:
      - job:
        dependsOn: [ 'setup' ]

        displayName: ${{unit.vmImage}} ${{value}}

        pool:
          vmImage: ${{unit.vmImage}}

        variables:
          JAVA_TOOL_OPTIONS: ${{image.javaToolOptions}}

        steps:
        - task: Cache@2
          displayName: Cache maven artifacts
          inputs:
            key: maven | $(Build.BuildId) | artifacts
            path: $(MAVEN_CACHE_FOLDER)
        - template: cache-target-tasks-template.yml
          parameters:
            modules:
              - ${{ value }}
          # Runs 'mvn install'
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -pl ${{value}} -Djacoco.skip=${{image.skipJaCoCo}}'
            mavenOptions: '-Xmx768m -Dmaven.resolver.transport=wagon'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '${{unit.jdkVersion}}'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'test'